### ISSUE TITLE
AdminLTE Boilerplate 5.4 goes to ‘404’

### ISSUE THREAD

**Issue by JKChen** [InfyOmLabs/adminlte-generator#13]
`https://github.com/InfyOmLabs/adminlte-generator/tree/5.4`
goes to the page of **404**

**Comment by qcol** [comment]
Indeed, this page of doc: http://labs.infyom.com/laravelgenerator/docs/5.4/boilerplates
gives 404

![zaznaczenie_087](https://user-images.githubusercontent.com/358993/27126745-c26a6b9e-50f8-11e7-87f1-d38066b3d6d0.png)

**Comment by mitulgolakiya** [comment]
just pushed th repo.
