### ISSUE TITLE
Failed installation, many issues

### ISSUE THREAD

**Issue by GlobSolutions** [InfyOmLabs/adminlte-generator#16]
i tried to install this using current project, but got error message that i need to have php7 , again i used this boilerpalte , download and run the install command, after that documentation finished no further instructions, tried to login error encryption, soved by genrate key and clear, working again try to login no database installed, dont know where to go or how to solve this. documentation usesless in this case

**Comment by skys215** [comment]
This should be a laravel question.
See laravel documentation first.

**Comment by mitulgolakiya** [comment]
@GlobalSolutions2018 we need some more details on what version you are trying. What exact error you are getting because it's installed by thousands of developers so far and no one reported this kind of bugs.

Post some more details on errors you are getting.

**Comment by GlobSolutions** [comment]
thank you guys, i guess some issues with laravel & windows, it is fine now
