### ISSUE TITLE
Error when running composer install

### ISSUE THREAD

**Issue by FacundoMainere** [InfyOmLabs/adminlte-generator#2]
When running "composer install" i get the following error: 

```
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize


  [ErrorException]                                                                                                                     
  file_put_contents(/home/facundo/Code/altura/backend/bootstrap/cache/services.php): failed to open stream: No such file or directory  


Script php artisan optimize handling the post-install-cmd event returned with error code 1
```

I checked https://github.com/InfyOmLabs/bootstrap-generator and it's not happening there

**Comment by w0rd-driven** [comment]
That's because there is no bootstrap/cache/ folder like the one that exists in the bootstrap template: https://github.com/InfyOmLabs/bootstrap-generator/tree/5.2/bootstrap/cache.

If you added that folder in manually the artisan command should work.
