### ISSUE TITLE
Change adminlte templates

### ISSUE THREAD

**Issue by EmmanuelAcuna** [InfyOmLabs/adminlte-generator#25]
is possible to change admilte for another dashboard like adminator?

**Comment by mitulgolakiya** [comment]
@EmmanuelAcuna yes, you can create your own repo. try to define templates the same way like adminlte-templates and configure generator to you your templates.

see configuration [here](https://github.com/InfyOmLabs/laravel-generator/blob/develop/config/laravel_generator.php#L80)
