### ISSUE TITLE
a small bug in BaseRepository.php and a little question

### ISSUE THREAD

**Issue by clms2** [InfyOmLabs/adminlte-generator#26]
`app/Repositories/BaseRepository.php` in line 91:`$query->skip($limit);`, I think here should be:`$query->limit($limit);`
and by the way, in old version like laravel 5.2, the `infyomlabs/laravel-generator ` will generate a criteria in controller like : `$this->goodsRepository->pushCriteria(new RequestCriteria($request));`, but in this version it has been removed, without criteria then original query string is needed, but I have wrote a little script to make criteria works well, so that is wasted,QAQ. and normal query string like 'a=1&b=2',if add c query param,it will need development in both front end and back end, but old version I wrote some script to improve the development speed, and it just need front end development,its more convenient for dev

**Comment by mitulgolakiya** [comment]
@clms2 limit thing is fixed. probably you should review this comment. https://github.com/InfyOmLabs/laravel-generator/issues/602#issuecomment-473904314
