### ISSUE TITLE
Pagination not generated

### ISSUE THREAD

**Issue by ganjarsetia** [InfyOmLabs/adminlte-generator#4]
How to generate pagination automatically?

when I run the generator via CLI with option `--paginate=10` the pagination is not genarated.

so I manually add

```
@include('adminlte-templates::common.paginate', ['records' => $records_in_DB])
```

**Comment by hijaumuda** [comment]
crud generator
--paginate=10

view:
{!! $model->render() !!}

**Comment by ShaileshLadumoR** [comment]
http://labs.infyom.com/laravelgenerator/docs/5.3/generator-options
