### ISSUE TITLE
Nothing on earth make this App works and installable, errors every where wvery method

### ISSUE THREAD

**Issue by Measne** [InfyOmLabs/adminlte-generator#47]
Tried for more than 10 hours to install this App, nothing works, no documentation befits, no video works, nothing on earth can make this work, errors every where every method

tried follow your unclear documentation
looks like alot off steps missing we should just imagine them
tried to find another installation guide, doesnt work errors and 
dont know why you made all this and failed just to make it download/go
wasting time

**Comment by ShaileshInfyom** [comment]
@Measne what error you getting?
>looks like alot off steps missing we should just imagine them

this is boilerplate and already configured and no need to do any thing for installation. you need to do just composer install and set databese. its works fine. 
i just download and do 4 step

1. composer install
2. set db in to env
3. run migration 
4. run an application and its working fine.

![image](https://user-images.githubusercontent.com/28335166/59083603-a9f16980-8915-11e9-86f2-0c4aca1281b4.png)

**Comment by Measne** [comment]
following 3 errors , on on composer install, second on migration, third on running
![1](https://user-images.githubusercontent.com/51411936/59084284-41998c80-8903-11e9-9424-c091421f37e1.png)
![2](https://user-images.githubusercontent.com/51411936/59084285-41998c80-8903-11e9-9d6c-f9c054b457bc.png)
![3](https://user-images.githubusercontent.com/51411936/59084286-42322300-8903-11e9-924a-c0eacf30c93e.png)

**Comment by ShaileshInfyom** [comment]
you need to generate key into env file. you can generate it by `php artisan key:generate` you should read https://laravel.com/docs/5.8/installation or google it. error related to laravel not generator.

**Comment by Measne** [comment]
the net result it needs a lot of missing steps, and it is not installed, you can say anything, but also you can make documentation , anyway i read everything in laravel installation, and it works fine because it is well documented, nothing missing and all projects works fine , except yours... thank you

**Comment by ShaileshInfyom** [comment]
@Measne it's Laravel stuff and Laravel already documented in his official site. no need doc for this boilerplate cause already we had  configured everything related to generator.  or if you want to use generator into your existing project then you can configure it manually and documented here http://labs.infyom.com/laravelgenerator/docs/5.8/installation. and you getting error related to Laravel installation step not generator 
![image](https://user-images.githubusercontent.com/28335166/59085022-d9ef3b80-891a-11e9-944f-03b46593eddb.png)

**Comment by Measne** [comment]
move on please,  i t works now, login page,  no credentials anywhere so i registered and logged in, again it is a blank control panel, there is menu with no buttons only profile logout , so how does this work, what mistake i did here
![5](https://user-images.githubusercontent.com/51411936/59085784-63e1d900-8908-11e9-98a7-5c65c9960530.png)

**Comment by ShaileshInfyom** [comment]
@Measne  everything is good. now you can generate any CRUD using generator. go on official doc please.
