### ISSUE TITLE
Override stub

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/adminlte-generator#48]
Hi!
Is it possible to modify/override/use_alternate stub for generating controllers? In my case, I want to add access control, for that, I add a method for checking in each action method in order to verify if the user is authorized.
Thanks!

**Comment by ShaileshInfyom** [comment]
you can fork a repo and do change as per your requirement.

**Comment by mitulgolakiya** [comment]
@dhcmega if you want to modify stub then just use publish templates options and modify the stub files you want to. http://labs.infyom.com/laravelgenerator/docs/5.8/publish-templates

Don't forget to delete stub files that you do not want to modify.

**Comment by dhcmega** [comment]
Perfect, I will publish templates. Missed that one. Thanks!!
