### ISSUE TITLE
problem with installing darkaonline/l5-swagger on laravel 5.6 template

### ISSUE THREAD

**Issue by amirreza1751** [InfyOmLabs/adminlte-generator#54]
I have cloned the 5.6 branch and tried to install **darkaonline/l5-swagger 5.6** which customized for laravel 5.6 and got this error: 
   _**Problem 1                                                                                                                               - Installation request for laravel/framework (locked at v6.0.0, required as ^6.0) -> satisfiable by laravel/framework[v6.0.0].        - darkaonline/l5-swagger 5.6.0 requires laravel/framework 5.6.* -> satisfiable by laravel/framework[5.6.x-dev]**_

**but when I try to install swagger on a fresh laravel 5.6 project it successfully installs.
What I want to use is infyom api_scaffold generator and swagger api documentation.**

thanks for your help.

**Comment by mitulgolakiya** [comment]
@amirreza1751 based on the error, it looks like you have laravel/framework 6 installed. But when I see the 5.6 branches for this repo, it has laravel 5.6 only. https://github.com/InfyOmLabs/adminlte-generator/blob/5.6/composer.json#L17

I would say you double-check your repo. Or if possible paste your composer.json here.

**Comment by amirreza1751** [comment]
Thank you and sorry. because that was my mistake. I had cloned the wrong branch and that caused the problem.
