### ISSUE TITLE
app does not use the Laravel 7 .env.example

### ISSUE THREAD

**Issue by rabol** [InfyOmLabs/adminlte-generator#67]
Not a big issue, but the .env.example is not using the laravel v7 version.

missing 
MAIL_FROM_NAME=${APP_NAME}
MAIL_FROM_ADDRESS=null

**Comment by vishalinfyom** [comment]
@rabol its already there. please check proper.

https://github.com/InfyOmLabs/coreui-generator/blob/7.0/.env.example
https://github.com/InfyOmLabs/adminlte-generator/blob/7.0/.env.example

**Comment by rabol** [comment]
Sorry, I just assumed that the default branch was the v7, but now I can see that the default branch is v6

**Comment by mitulgolakiya** [comment]
I just changed the default branch to 7.0
