### ISSUE TITLE
Installation steps are not correct

### ISSUE THREAD

**Issue by rabol** [InfyOmLabs/adminlte-generator#68]
The installation steps are not correct:

https://labs.infyom.com/laravelgenerator/docs/7.0/boilerplates

One cannot do the php artisan key:generate before the composer install command is complete

Steps should be something like:

cp .env.example .env
<edit .env>
composer install
php artisan key:generate
php artisan migrate --seed
php artisan storage:link

**Comment by vishalinfyom** [comment]
Hii @rabol we have re-write our site with updated documentations.

Hope this link will resolve your issue.

https://www.infyom.com/open-source/laravelgenerator/docs/7.0/boilerplates

Thanks
