### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by rabol** [InfyOmLabs/adminlte-generator#69]
during the composer install process:

Deprecation Notice: Class InfyOm\Generator\Generators\Vuejs\RoutesGenerator located in ./vendor/infyomlabs/laravel-generator/src/Generators/VueJs/RoutesGenerator.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class InfyOm\Generator\Generators\API\TestGenerator located in ./vendor/infyomlabs/laravel-generator/src/Generators/VueJs/TestGenerator.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by vishalinfyom** [comment]
@rabol which version of generator `6.0` / `7.0` you are using ??

**Comment by rabol** [comment]
Sorry for not mentioning that: 7.0 I assume - Latest
