### ISSUE TITLE
Laravel v7 email verification

### ISSUE THREAD

**Issue by rabol** [InfyOmLabs/adminlte-generator#70]
I'm trying to get the email verification from Laravel working with this app

I'm using Homestead
so I have a http://test.test

Steps:

git clone https://github.com/InfyOmLabs/adminlte-generator.git test
cd test
cp .env.example .env
nano .env (Modify and save)
composer install
php artisan key:generate
php artisan migrate:fresh --seed
php artisan storage:link
modify the User model to implements MustVerifyEmail (as pr. https://laravel.com/docs/7.x/verification) 
open browser and navigate to http://test.test
click the 'Register' in the menu
register user 'Admin admin', admin@admin.com, password
I get redirected to /home with a screen saying that my email needs to be verified
I click the link to request 

and get this error:

Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: POST.
http://test.test/email/resend

**Comment by rabol** [comment]
Looks like it is the: adminlte-generator/resources/views/auth/verify.blade.php that is the issue

There is no form, but a 'href'

**Comment by ShaileshInfyom** [comment]
#70 issue has been fixed in 7.0 with PR https://github.com/InfyOmLabs/adminlte-generator/pull/91 and 8.0 with PR #90  both
