### ISSUE TITLE
Suggestion: move "infyomlabs/laravel-generator": "7.0.x-dev" to the require-dev

### ISSUE THREAD

**Issue by rabol** [InfyOmLabs/adminlte-generator#71]
Consider moving: "infyomlabs/laravel-generator": "7.0.x-dev", to the require-dev sections so that the 'builder is not in a production environment

**Comment by vishalinfyom** [comment]
HIi @rabol we have now separate versions of admin lte generator as per Laravel versions.

So by using require-dev you will get latest laravel version boiper plate and if you want laralve 7 boiper plate then you can use 7.0.x-dev.

Thanks for your feedback.
