### ISSUE TITLE
Failing to open anything, following installation guide

### ISSUE THREAD

**Issue by fmgrafikdesign** [InfyOmLabs/adminlte-generator#74]
Hello everyone,

I'm trying to follow the simple steps from https://labs.infyom.com/laravelgenerator/docs/7.0/boilerplates but I get an error in the key:generate command already:
```PHP Fatal error:  require(): Failed opening required 'D:\*omitted*\adminlte-generator/vendor/autoload.php' (include_path='.;C:\php\pear')```

I noticed how the path changes from backslashes "\" to slashes "/" and I'm wondering if that's an issue with Windows or something?

**Comment by fmgrafikdesign** [comment]
I fixed this by first running composer dump-autoload and then running composer install, before running the artisan key:generate command. Maybe your docs are a bit wrong there, or you're relying on Unix file structure or something.

**Comment by ShaileshInfyom** [comment]
@fmgrafikdesign as per your comment. the issue has been resolved.
