### ISSUE TITLE
Datatables not showing anything

### ISSUE THREAD

**Issue by RayhanYulanda** [InfyOmLabs/adminlte-generator#75]
I tried to add, it works perfectly and added in my database but i cant see my data in datatables

**Comment by mitulgolakiya** [comment]
Maybe this video can help you: https://www.youtube.com/watch?v=YC0YXrAF4SA

Or re-open the issue with more details please.

**Comment by RayhanYulanda** [comment]
I have followed what the video did but still cant work @mitulgolakiya

**Comment by mitulgolakiya** [comment]
@RayhanYulanda Please post the exact error that you are getting.

**Comment by versatilegurung** [comment]
I tried everything but am unable to get datatables, can you help how can this be acheived?

**Comment by mlajx** [comment]
I think I found out why this is happening.

When a file is generated by the infyom command, `resources/views/{name}/table.blade.php` is created and there are:

```blade
@push('third_party_scripts')
    @include ('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush
```

but `@push` is used for `@stack` ([doc](https://laravel.com/docs/8.x/blade#stacks)) and `resources/views/templates/app.blade.php` has `@yield('third_party_scripts')`.

So when I change `@yield('third_party_scripts')` to `@stack('third_party_scripts')`, the table worked normally.
