### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by leocharrua** [InfyOmLabs/adminlte-generator#76]
Hello, first of all, thank you for your work. 
I consider it very important to have a demo application, to see all the functionality of the product and the final results.
I am also interested in knowing how define filters and column sorting in lists.
How do you use specific controls for fields, for example select2?
Thank you very much

**Comment by alphaolomi** [comment]
+1

**Comment by mitulgolakiya** [comment]
@leocharrua thank you for your kind words. Actually we think that demo is not needed and the reason for that is, it's completely the same as AdminLTE. This is not a kind of application with a bunch of features. It's boilerplate for getting started with the AdminTLE theme with the Laravel Generator. so demo of the AdminLTE theme does the same job.

**Comment by leocharrua** [comment]
Hello @mitulgolakiya, thanks for your answer ... I like your product because it generates clean code and has the generator templates to adapt to my needs. By the way, I'm looking at them now and I think the product has a lot of potential. For example, select or select2 (with AJAX) could be added for foreign keys in forms, in lists you could add the description of the foreign key fields and also filters for the columns. I wish I could add this, but without breaking your code (extending it maybe), so that my code can still be compatible with your version. What do you think? (sorry by my english)

**Comment by leocharrua** [comment]
Hello. Do you have any opinion about that? Is there any roadmap for adminlte-generator? Thanks
