### ISSUE TITLE
MySQLDriver

### ISSUE THREAD

**Issue by mykinde** [InfyOmLabs/adminlte-generator#79]
Class 'Doctrine\DBAL\Driver\AbstractMySQLDriver' not found

  at C:\xampp\htdocs\adminlte-generator-8.0\vendor\laravel\framework\src\Illuminate\Database\PDO\MySqlDriver.php:8
      4▕
      5▕ use Doctrine\DBAL\Driver\AbstractMySQLDriver;
      6▕ use Illuminate\Database\PDO\Concerns\ConnectsToDatabase;
      7▕
  ➜   8▕ class MySqlDriver extends AbstractMySQLDriver
      9▕ {
     10▕     use ConnectsToDatabase;
     11▕ }
     12▕

  1   C:\xampp\htdocs\adminlte-generator-8.0\vendor\composer\ClassLoader.php:444
      include()

  2   C:\xampp\htdocs\adminlte-generator-8.0\vendor\composer\ClassLoader.php:322
      Composer\Autoload\includeFile("C:\xampp\htdocs\adminlte-generator-8.0\vendor\composer/../laravel/framework/src/Illuminate/Database/PDO/MySqlDriver.php")
PS C:\xampp\htdocs\adminlte-generator-8.0>

**Comment by mjsorribas** [comment]
I've fixed with this:
` composer require doctrine/dbal`
please review my commit : https://github.com/InfyOmLabs/adminlte-generator/commit/5ab233a4edf57637f2665bc9e951e69eb13414c4
or my pr https://github.com/InfyOmLabs/adminlte-generator/pull/80
