### ISSUE TITLE
Open Generator Builder

### ISSUE THREAD

**Issue by fredroo** [InfyOmLabs/adminlte-generator#8]
![erro](https://cloud.githubusercontent.com/assets/6863089/21226814/581a187a-c2be-11e6-9ec7-ca3e60963ced.png)
how open generator_builder in browser

what the url path

**Comment by globetour** [comment]
i have the question too.the install guide have some trouble

**Comment by lherich** [comment]
__TL;DR__
Just run both commands and hit reload:
```php
php artisan key:generate
php artisan confg:cache
```

---

There is no .env file and the default options do not show errors. So:
1) `cp .env.example .env`
2) Open .env and set "APP_DEBUG=true"
3) Refresh the webpage in your browser and you will se the error messages
4) To solve the error itself, you need to generate a proper secret key. See https://github.com/laravel/framework/issues/9080
Just run:
```php
php artisan key:generate
php artisan confg:cache
```
