### ISSUE TITLE
Datatables are not working.

### ISSUE THREAD

**Issue by versatilegurung** [InfyOmLabs/adminlte-generator#82]
when 
php artisan infyom:scaffold Post --datatables=true

this doesnot up show any erros but in browser datatables are not visible.

**Comment by balmacefa** [comment]
You need to publish datatables-buttons and html
Run ` artisan vendor:publish --tag=datatables-buttons --force`
and ` artisan vendor:publish --tag=datatables-html`

**Comment by mitulgolakiya** [comment]
You can follow this video tutorial if anyone else got any issues. https://www.youtube.com/watch?v=YC0YXrAF4SA 

Also other various video tutorials are available on this channel related to InfyOm and DataTable with InfyOm.

Great work done by @shailesh-ladumor
