### ISSUE TITLE
AdminLTE layout is not correct

### ISSUE THREAD

**Issue by rxng** [InfyOmLabs/adminlte-generator#84]
The elements are all showing up with bad formatting, e.g. text fields too narrow etc

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/19649766/118215414-d5dbd900-b4b4-11eb-9cdd-b60c4ead2053.png">

**Comment by YasserSB** [comment]
Facing same issue, is there any solution about this?

**Comment by ShaileshInfyom** [comment]
fixed in PR https://github.com/InfyOmLabs/adminlte-generator/pull/90
