### ISSUE TITLE
Target class [UserController] does not exist.

### ISSUE THREAD

**Issue by jadavpalak** [InfyOmLabs/adminlte-generator#85]
When run commnd `php artisan infyom.publish:user`  it executes successfully.

but when click on user menu getting below error.

![image](https://user-images.githubusercontent.com/25167163/121917623-ef41a080-cd52-11eb-8bbe-7890d54c68a5.png)

![image](https://user-images.githubusercontent.com/25167163/121917276-96720800-cd52-11eb-9b93-9c49ff2f1be1.png)

**Comment by Giovanni-Petrella** [comment]
Solution https://www.youtube.com/watch?v=NMNZBCZWtDA but this not positive for Infyom

**Comment by vishalinfyom** [comment]
Thanks @Giovanni-Petrella for providing that video link.

@jadavpalak we hope that your issue was resolved.

Thanks
